name: CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  # https://github.com/chipsec/chipsec/tags
  CHIPSEC_TAG: 1.9.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fdisk efitools uuid debootstrap -y --no-install-recommends

      - name: Checkout repository  
        uses: actions/checkout@v4
        
      - name: Generate keys
        run: sudo ./tools/gen-keys.sh 
        
      - name: Build ISO
        run: sudo ./tools/create-chipsec.sh -d /tmp/Chipsec-Check-${{ github.ref_name }}.iso -c ${{ env.CHIPSEC_TAG }}
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ISOs
          path: /tmp/*.iso
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            /tmp/*.iso
