name: CI

on:
  push:
    branches:
    - master
    tags:
      - '*'
  workflow_dispatch:

env:
  # https://github.com/chipsec/chipsec/tags
  CHIPSEC_TAG: 1.8.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fdisk efitools uuid -y --no-install-recommends

      - name: Checkout repository  
        uses: actions/checkout@v3
        
      - name: Set version
        id: set_version
        run: echo "::set-output name=release_version::${GITHUB_REF/refs\/tags\//}"
        
      - name: Generate keys
        run: sudo ./tools/gen-keys.sh 
        
      - name: Build ISO
        run: sudo ./tools/create-chipsec.sh -d /tmp/output.iso -c ${{ env.CHIPSEC_TAG }}
