name: CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  # https://github.com/chipsec/chipsec/tags
  CHIPSEC_TAG: 1.8.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get full-upgrade -y
          sudo apt install sbsign efitools dosfstools git -y --no-install-recommends

      - name: Checkout repository  
        uses: actions/checkout@v3
        
      - name: Set version
        id: set_version
        run: echo "::set-output name=release_version::${GITHUB_REF/refs\/tags\//}"
        
      - name: Build ISO
        run: ./tools/create-chipsec.sh -d /tmp/Chipsec-Check-${{ steps.set_version.outputs.release_version }}.iso -c ${{ env.CHIPSEC_TAG }}
